Add basic support for Yaml-configuration-files
phlib/console-configuration pull request #2
Opened 2017-03-01 19:00 UTC by Fahrenholz

- when specified, file extension can be either php or yml
- when detected, file extension has to be php
- yml-files are read using symfony/yaml
- 2 tests added (yml file config specification and specification of unsupported configuration) in order to preserve the 100% code coverage the library had.

2017-03-02 17:04 UTC, chrisminett requested changes
Thanks for the submission! It would be good to support more config file types!

I've added a few in-line comments to the changes. If you can take a look at these, we'd be happy to review any changes!

2017-03-02 17:04 UTC, chrisminett commented on src/Helper/ConfigurationHelper.php
> +
I don't see the need to store the result to a variable immediately before returning the value.

However, more importantly is that this won't handle a Yaml file (set via `$options['filename']`). I think this should be something like `return $this->getConfigurationArray($filePath);`

2017-03-02 17:04 UTC, chrisminett commented on src/Helper/ConfigurationHelper.php
> +        try {
No need for a try/catch here, can just return directly. Good to add the `@throws` though!

2017-03-02 17:04 UTC, chrisminett commented on tests/Helper/ConfigurationHelperTest.php
> +use Doctrine\Instantiator\Exception\UnexpectedValueException;
Shouldn't be importing this. See line 133

2017-03-02 17:04 UTC, chrisminett commented on tests/Helper/ConfigurationHelperTest.php
> +     * @expectedException UnexpectedValueException
Missing `\` (which is why it's using the Doctrine import)

2017-03-02 17:04 UTC, chrisminett commented on src/Helper/ConfigurationHelper.php
> +        } elseif ($extension === 'yml') {
I think that `.yaml` is also a valid extension, so it would be good to support it here!

2017-03-02 17:04 UTC, chrisminett commented on tests/Helper/files/cli-config.lala
> +something wrong
Please make sure your IDE is set to *Ensure line feed at file end on Save* (ex. JetBrains, or similar!)

2017-03-02 22:15 UTC, Fahrenholz commented on src/Helper/ConfigurationHelper.php
> +        } elseif ($extension === 'yml') {
correct. Will be done in next commit.

2017-03-02 22:16 UTC, Fahrenholz commented on tests/Helper/ConfigurationHelperTest.php
> +use Doctrine\Instantiator\Exception\UnexpectedValueException;
fixed in next commit

2017-03-02 22:16 UTC, Fahrenholz commented on tests/Helper/ConfigurationHelperTest.php
> +     * @expectedException UnexpectedValueException
also fixed.

2017-03-02 22:18 UTC, Fahrenholz commented on tests/Helper/files/cli-config.lala
> +something wrong
yeah, sorry for that.

2017-03-02 22:55 UTC, Fahrenholz commented
Voilà! I changed everything as requested. I'm not quite sure that the tool, as it is now, could ever detect any .yml-file. But I think it's a feature that can be implemented in any next incrementation if needed.

2017-03-03 10:02 UTC, chrisminett approved these changes

2017-03-03 10:04 UTC, merged